name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Release to latest/candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: canonical/charming-actions/release-libraries@2.5.0-rc
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: canonical/charming-actions/channel@2.5.0-rc
        id: candidate

      - uses: canonical/charming-actions/upload-charm@2.5.0-rc
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "latest/candidate"
